### ISSUE TITLE
Problem with the compilation of Delft3d

### ISSUE THREAD

**Issue by carmenafa** [veethahavya-CU-cz/delft3dfm_dockerized#2]
Hi, first thank you for uploading this repository to be able to compile Delft3D. 
I don't have too much experience compiling code and I need to have Delft3D to be able to continue with my thesis. I have tried to install it with different tutorials but I have not been successful. I have installed in my virtual machine Centos 7, after that I have followed the steps that you indicate in Centos_7_intel_basic but it gives me error when I do the ./configure to compile hdf5. The error is as follows:
./configure: line 4533: mpiicc: command not found.
I don't understand why it is not found because before I have loaded the variables with source and when I do a which mpiicc it tells me that it is in /opt/intel/oneapi/mpi/2021.7.1/bin/mpiicc.
On the other hand, another doubt that arises is that when checking that I have installed all the compilers I realize that I have not installed mpiicxx but mpicxx, is there any difference?
I would really appreciate a rather swift reply on this as I’m currently needed to use Delft3d in a project.

Thank you very much in advance for your support! 😊

Best,
Carmen

**Comment by veethahavya-CU-cz** [comment]
Hi Carmen,

Unfortunately, I do not have the time to look into your issue personally. However, I understand your frustration with compiling the code, which is why I created this repositry.

I can only advise to use the docker container which can be built with the instructions provided in the readme, instead of trying to compile it on a VM.
Feel free to get back to me if there are any issues building the docker container.
